name: lint all
on: pull_request
env:
  PRISMA_TELEMETRY_INFORMATION: "prisma-client-go lint.yml"

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: '1.19'

      - uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-

      - name: download
        if: steps.changes.outputs.go == 'true'
        run: go mod download

      - name: generate
        if: steps.changes.outputs.go == 'true'
        run: go generate ./...

      - name: install golangci-lint
        if: steps.changes.outputs.go == 'true'
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.50.0

      - name: run linter
        if: steps.changes.outputs.go == 'true'
        run: ./bin/golangci-lint run ./... --timeout "5m0s" --enable "gofmt,revive,exportloopref,gocritic"
