name: test all
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
env:
  PRISMA_TELEMETRY_INFORMATION: "prisma-client-go test.yml"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-go@v2
        with:
          go-version: '1.14'

      - name: deps
        run: go mod download

      - name: generate
        run: go generate ./...
        env:
          DEBUG: "*"
          PHOTON_GO_LOG: true

      - name: setup
        run: go run ./test/setup/init setup
        env:
          PHOTON_GO_LOG: true

      - name: test
        run: go test ./... -v
        env:
          PHOTON_GO_LOG: true
